---
- name: Add a new VRF to a tenant
  aci_vrf:
    hostname: {{ inventory_hostname }}
    vrf: vrf_lab
    tenant: infra
    descr: Lab VRF
    policy_control_preference: enforced
    policy_control_direction: ingress
    state: present
    validate_certs: false