---
- name: Add a new VRF to a tenant
  aci_vrf:
    hostname: 172.16.1.42
    username: admin
    password: admin123
    vrf: vrf_lab
    tenant: infra
    descr: Lab VRF
    policy_control_preference: enforced
    policy_control_direction: ingress
    state: present
    validate_certs: false