---
- name: Create a Snapshot
  aci_config_snapshot:
    hostname: {{ inventory_hostname }}
    state: present
    export_policy: config_backup
    max_count: 10
    description: Backups taken before new configs are applied.
    validate_certs: false