---
- name: Create a Snapshot
  aci_config_snapshot:
    hostname: 172.16.1.42
    username: admin
    password: admin123
    state: present
    export_policy: config_backup
    max_count: 10
    description: Backups taken before new configs are applied.
    validate_certs: false